name: Soumik Roy
favicon: null
layout_spectrum: 0.24283
typography_spectrum: 0.74148
title: Soumik Roy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#7a5413'
    - '#b49e7a'
    - '#d5c9b4'
  brandStrength: 0.9853165184613317
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
